version: "2"
linters:
  enable:
    - gocritic
    - gocyclo
    - misspell
  settings:
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test\.go
        text: Error return value is not checked
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
