name: Lint
on:
  push:
    branches: [main]
    paths:
      - "cmd/**"
      - "internal/**"
  pull_request:
  repository_dispatch:
    types: ["Lint"]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Set up Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: go.mod

      - name: Install Task
        uses: arduino/setup-task@c0bc642852239c2689f73f4ea6459c29405f3c52 # v3.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install golangci-lint
        run: task -p deps:install:golangci-lint

      - name: Lint
        run: task lint

  notification:
    needs:
      - lint
    name: Notification
    if: always()
    uses: werf/common-ci/.github/workflows/notification.yml@3cbc92fa058bac285b05135387110dbfc68ffcbc # main
    secrets:
      loopNotificationGroup: ${{ secrets.LOOP_NOTIFICATION_GROUP }}
      webhook: ${{ secrets.LOOP_NOTIFICATION_WEBHOOK }}
      notificationChannel: ${{ secrets.LOOP_NOTIFICATION_CHANNEL }}
